version: '3'

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ~/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - app1
            - app2

    app1:
        image: httpd

    app2:
        image: httpd
